language: node_js
node_js:
  - "node"
  - "6"
services:
  - mysql
before_script:
  - cd app
  - npm install
  - cd database
  - chmod +x ./travisMysqlSetup.sh
  - mysql -uroot --password="" < SP_TableSetup.sql
script:
  - npm run test-cov
after_success:
  - npm run coverage